/**
 * API Types — re-exports from generated types with compatibility aliases.
 *
 * Generated by @hey-api/openapi-ts from FastAPI OpenAPI spec.
 * Source of truth: apps/api/app/schemas/*.py → openapi.json → types.gen.ts
 *
 * This file provides stable import paths for hooks and pages.
 * When generated types change field names, update aliases HERE — not in 20 files.
 */

export type {
  EventCreate,
  EventResponse,
  RegistrationResponse,
  OrganizationCreate,
  OrganizationResponse,
  QuestionOut,
  SessionOut,
  AssessmentResultOut,
  AuthResponse,
} from "./generated/types.gen";

// ── AuraScore (compatibility alias) ──
// Generated type is `AuraScoreResponse` with `overall_score` / `elite_status`
// Hooks and dashboard use `AuraScore` with `total_score` / `is_elite`
// This adapter keeps existing code working while we migrate
import type { AuraScoreResponse } from "./generated/types.gen";

export type BadgeTier = "platinum" | "gold" | "silver" | "bronze" | "none";

export type AuraScore = {
  volunteer_id: string;
  total_score: number;          // maps from overall_score
  badge_tier: BadgeTier;
  is_elite: boolean;            // maps from elite_status
  competency_scores: Record<string, number>;
  verification_level?: string;
  last_updated?: string;
  // Raw fields from API
  reliability_score?: number;
  reliability_status?: string;
  events_attended?: number;
  events_no_show?: number;
  percentile_rank?: number | null;
  aura_history?: unknown[];
  calculated_at?: string | null;
};

/** Transform API response to AuraScore used by hooks */
export function toAuraScore(raw: AuraScoreResponse): AuraScore {
  return {
    volunteer_id: raw.volunteer_id,
    total_score: raw.overall_score,
    badge_tier: (raw.badge_tier as BadgeTier) || "none",
    is_elite: raw.elite_status,
    competency_scores: raw.competency_scores,
    reliability_score: raw.reliability_score,
    reliability_status: raw.reliability_status,
    events_attended: raw.events_attended,
    events_no_show: raw.events_no_show,
    percentile_rank: raw.percentile_rank,
    aura_history: raw.aura_history,
    calculated_at: raw.calculated_at,
  };
}

// ── Profile (compatibility alias with default values) ──
import type { ProfileResponse } from "./generated/types.gen";

export type Profile = {
  id: string;
  username: string;
  display_name: string | null;
  avatar_url: string | null;
  bio: string | null;
  location: string | null;
  languages: string[];
  is_public: boolean;
  badge_tier?: BadgeTier;
  created_at: string;
  updated_at: string;
};

/** Transform API ProfileResponse to Profile with safe defaults */
export function toProfile(raw: ProfileResponse): Profile {
  return {
    id: raw.id,
    username: raw.username,
    display_name: raw.display_name ?? null,
    avatar_url: raw.avatar_url ?? null,
    bio: raw.bio ?? null,
    location: raw.location ?? null,
    languages: raw.languages ?? [],
    is_public: raw.is_public ?? false,
    created_at: raw.created_at,
    updated_at: raw.updated_at,
  };
}

export type { ProfileUpdate as UpdateProfileRequest } from "./generated/types.gen";

// ── Badge ──
// No generated Badge type for list — API returns raw from Supabase
export interface Badge {
  id: string;
  volunteer_id: string;
  badge_type: string;
  tier: string;
  earned_at: string;
  metadata: Record<string, unknown>;
}

// ── Activity ──
export interface ActivityItem {
  id: string;
  type: "assessment" | "event" | "verification" | "badge";
  description: string;
  created_at: string;
  metadata: Record<string, unknown>;
}

// ── Dashboard Stats ──
export interface DashboardStats {
  events_attended: number;
  total_hours: number;
  verified_skills: number;
  streak_days: number;
}
