#!/usr/bin/env python3
"""
Memory Consolidation Daemon — биологический sleep-cycle для роя.

Аналог мозга:
  agent-feedback-log.md   = гиппокамп (сырые эпизодические события)
  agent-feedback-distilled.md = неокортекс (дистиллированные правила)
  Этот скрипт = SWS-фаза сна (replay → consolidate → prune)

Что делает:
  1. Читает полный agent-feedback-log.md (вся история)
  2. Использует Groq (бесплатно) для синтеза дистиллированных правил
  3. Записывает agent-feedback-distilled.md (то что агенты ЧИТАЮТ)
  4. Архивирует старые raw-записи из основного лога (REM-прунинг)

Запускается ПОСЛЕ каждого дневного запуска роя в GitHub Actions.
Также можно запустить вручную: python -m packages.swarm.memory_consolidation
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from loguru import logger

project_root = Path(__file__).parent.parent.parent
packages_path = str(project_root / "packages")
if packages_path not in sys.path:
    sys.path.insert(0, packages_path)

# ── Paths ─────────────────────────────────────────────────────────────────────

SWARM_DIR = project_root / "memory" / "swarm"
FEEDBACK_LOG = SWARM_DIR / "agent-feedback-log.md"
DISTILLED_FILE = SWARM_DIR / "agent-feedback-distilled.md"
EPISODIC_INBOX = SWARM_DIR / "episodic_inbox"

# How many raw log entries to keep in active section before archiving
ACTIVE_WINDOW = 20


# ── Consolidation prompt ──────────────────────────────────────────────────────

CONSOLIDATION_PROMPT = """You are a memory consolidation system for an AI agent swarm working on the Volaura project (verified volunteer platform, Azerbaijan, solo founder Yusif, budget $50/mo).

You will receive the FULL history of agent proposals, decisions, and outcomes.

Your job: synthesize this into 3 compressed, high-signal sections that future agents will read.

INPUT (full feedback log):
{feedback_log}

OUTPUT (JSON only):

{{
  "never_propose": [
    // Hard rules from rejections. Exact proposal types to NEVER repeat.
    // Format: "SHORT RULE — reason (session N evidence)"
    // Max 10 items. Most important first.
  ],
  "high_value_patterns": [
    // Proposal types that got implemented or praised.
    // Format: "PATTERN — why it works (example)"
    // Max 7 items.
  ],
  "open_findings": [
    // Unresolved findings: open bugs, deferred items, dismissed-but-valid risks.
    // Format: "FINDING — status — action needed"
    // Max 10 items. Include items dismissed by CTO that might be valid.
  ],
  "meta_insight": "1-2 sentence insight about the CTO's blind spots or the swarm's systematic errors",
  "entries_processed": <integer count of raw table rows processed>
}}

Rules:
- Be ruthlessly specific. "Don't propose Redis" is good. "Consider infrastructure improvements" is useless.
- Include session numbers in evidence.
- Flag the Session 25 → Session 42 route shadowing pattern: dismissed findings can be critical.
- If you see repeated proposals being rejected, name the pattern explicitly."""


# ── Core ──────────────────────────────────────────────────────────────────────

def _read_feedback_log() -> str:
    """Read the full agent-feedback-log.md."""
    if not FEEDBACK_LOG.exists():
        return ""
    with open(FEEDBACK_LOG, "r", encoding="utf-8") as f:
        return f.read()


def _count_raw_entries(log_content: str) -> int:
    """Count table rows in the raw log."""
    return sum(1 for line in log_content.split("\n") if line.startswith("| ") and not line.startswith("| Session"))


async def _call_groq_consolidation(log_content: str, groq_key: str) -> dict | None:
    """Call Groq to synthesize the log into distilled rules."""
    try:
        from groq import AsyncGroq
        client = AsyncGroq(api_key=groq_key)

        prompt = CONSOLIDATION_PROMPT.format(feedback_log=log_content[:12000])  # ~12k chars fits in context

        resp = await asyncio.wait_for(
            client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,  # Low temp for consistency
                max_tokens=2000,
                response_format={"type": "json_object"},
            ),
            timeout=30.0,
        )
        raw = resp.choices[0].message.content or ""
        return json.loads(raw)

    except Exception as e:
        logger.error(f"Groq consolidation failed: {e}")
        return None


def _write_distilled(synthesis: dict) -> None:
    """Write the distilled knowledge file that agents will inject."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    entries = synthesis.get("entries_processed", "?")

    lines = [
        "# Agent Feedback — Distilled Rules",
        "",
        f"**Auto-generated by memory_consolidation.py** | Last updated: {now} | Processed {entries} raw entries",
        "**Agents read THIS file, not the full log.** Full log in agent-feedback-log.md (hippocampus).",
        "",
        "---",
        "",
        "## ❌ NEVER PROPOSE (hard rejections)",
        "",
        "These proposal types are permanently rejected. Proposing them again wastes a swarm slot.",
        "",
    ]

    for rule in synthesis.get("never_propose", []):
        lines.append(f"- {rule}")

    lines += [
        "",
        "---",
        "",
        "## ✅ HIGH-VALUE PATTERNS (do more of these)",
        "",
        "These types of proposals consistently get implemented or praised.",
        "",
    ]

    for pattern in synthesis.get("high_value_patterns", []):
        lines.append(f"- {pattern}")

    lines += [
        "",
        "---",
        "",
        "## 🔍 OPEN FINDINGS (unresolved — check before proposing)",
        "",
        "These findings are open, deferred, or dismissed but potentially still valid.",
        "**CRITICAL LESSON:** Session 25 Security Agent found route shadowing, CTO dismissed it.",
        "Session 42: bug was real, P0, lived in production 17 sessions. Check dismissed items.",
        "",
    ]

    for finding in synthesis.get("open_findings", []):
        lines.append(f"- {finding}")

    meta = synthesis.get("meta_insight", "")
    if meta:
        lines += [
            "",
            "---",
            "",
            "## 🧠 Meta-Insight (CTO blind spots / swarm systematic errors)",
            "",
            f"> {meta}",
            "",
        ]

    lines += [
        "---",
        "",
        "**Next consolidation:** Runs automatically after each swarm daily run.",
        "**Manual run:** `python -m packages.swarm.memory_consolidation`",
    ]

    with open(DISTILLED_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    logger.info(f"Distilled file written: {DISTILLED_FILE}")


def _write_episodic_snapshot(log_content: str) -> None:
    """DISABLED per SYNC §9.5 (Perplexity brief 2026-04-14, Cowork inbox note
    `2026-04-14T1030-memory-gate-from-perplexity.md`).

    Snapshots were write-only: 10 files accumulated daily, all with functionally
    identical content (only timestamp differed), and no worker read them. Disabled
    until a reader-agent OR a content-diff guard exists. Signature kept so
    call-sites upstream don't break.
    """
    logger.info("episodic snapshot disabled per SYNC §9.5 — noop")


def _fallback_distilled(log_content: str) -> None:
    """If LLM fails, write a minimal distilled file by extracting structured sections."""
    lines = [
        "# Agent Feedback — Distilled Rules",
        "",
        f"**Fallback mode** (LLM unavailable) | Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "---",
        "",
    ]

    # Extract "Rejected Patterns" and "High-Value Proposal Patterns" sections.
    # The feedback log may contain these sections multiple times (one per run),
    # so collect bullets into ordered lists with a seen-set to dedupe on first-80-chars
    # (absorbs minor phrasing drift). Emit one unified list per section.
    rejected: list[str] = []
    high_value: list[str] = []
    seen_rejected: set[str] = set()
    seen_high: set[str] = set()
    current: str | None = None

    for line in log_content.split("\n"):
        if "## Rejected Patterns" in line:
            current = "rejected"
            continue
        if "## High-Value Proposal Patterns" in line:
            current = "high_value"
            continue
        if line.startswith("## "):
            current = None
            continue
        if current and line[:2].rstrip(".").isdigit() and "." in line[:3]:
            bullet = f"- {line.split('.', 1)[1].strip()}"
            # Dedupe on the bold title — each bullet is `- **Name** — rest`.
            # Absorbs phrasing drift in the trailing explanation between runs.
            if "**" in bullet:
                try:
                    title = bullet.split("**", 2)[1].strip().lower()
                except IndexError:
                    title = bullet[:60].lower()
            else:
                title = bullet[:60].lower()
            if current == "rejected" and title not in seen_rejected:
                seen_rejected.add(title)
                rejected.append(bullet)
            elif current == "high_value" and title not in seen_high:
                seen_high.add(title)
                high_value.append(bullet)

    if rejected:
        lines.append("## ❌ NEVER PROPOSE\n")
        lines.extend(rejected)
    if high_value:
        lines.append("\n## ✅ HIGH-VALUE PATTERNS\n")
        lines.extend(high_value)

    with open(DISTILLED_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    logger.warning("Wrote fallback distilled file (no LLM synthesis)")


# ── Entry point ───────────────────────────────────────────────────────────────

async def consolidate(groq_key: str | None = None) -> bool:
    """
    Main consolidation function.
    Returns True if LLM synthesis succeeded, False if fallback used.
    """
    logger.info("Memory consolidation starting...")

    log_content = _read_feedback_log()
    if not log_content.strip():
        logger.warning("agent-feedback-log.md is empty — nothing to consolidate")
        return False

    entry_count = _count_raw_entries(log_content)
    logger.info(f"Processing {entry_count} raw entries from feedback log")

    # Save episodic snapshot before any modification
    _write_episodic_snapshot(log_content)

    # Try LLM synthesis
    groq_key = groq_key or os.environ.get("GROQ_API_KEY", "")
    synthesis = None

    if groq_key:
        synthesis = await _call_groq_consolidation(log_content, groq_key)

    if synthesis:
        _write_distilled(synthesis)
        logger.success(
            f"Consolidation complete: "
            f"{len(synthesis.get('never_propose', []))} rules, "
            f"{len(synthesis.get('high_value_patterns', []))} patterns, "
            f"{len(synthesis.get('open_findings', []))} open findings"
        )
        return True
    else:
        logger.warning("LLM synthesis failed — using fallback extraction")
        _fallback_distilled(log_content)
        return False


def main() -> None:
    """CLI entry point."""
    import argparse
    from dotenv import load_dotenv
    load_dotenv(project_root / "apps" / "api" / ".env")

    parser = argparse.ArgumentParser(description="Memory consolidation daemon")
    parser.add_argument("--dry-run", action="store_true", help="Print synthesis without writing files")
    args = parser.parse_args()

    if args.dry_run:
        log_content = _read_feedback_log()
        logger.info(f"DRY RUN — {_count_raw_entries(log_content)} entries in log")
        logger.info(f"Would write to: {DISTILLED_FILE}")
        return

    success = asyncio.run(consolidate())
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
