"""
Swarm Decision Engine — Type Definitions
All Pydantic v2 models for the universal multi-model decision engine.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class StakesLevel(str, Enum):
    LOW = "low"            # 3-5 agents
    MEDIUM = "medium"      # 7-10 agents
    HIGH = "high"          # 10-15 agents
    CRITICAL = "critical"  # 15+ agents


class DomainTag(str, Enum):
    CODE = "code"
    SECURITY = "security"
    BUSINESS = "business"
    UX = "ux"
    ARCHITECTURE = "architecture"
    OPERATIONS = "operations"
    DATA = "data"
    GENERAL = "general"


class PathDefinition(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    description: str
    best_case: str = ""
    worst_case: str = ""
    effort: str = ""  # S / M / L / XL


class SwarmConfig(BaseModel):
    question: str
    context: str = ""
    constraints: str = ""
    paths: dict[str, PathDefinition] | None = None  # None = agents generate paths
    stakes: StakesLevel = StakesLevel.MEDIUM
    domain: DomainTag = DomainTag.GENERAL
    temperature: float = 0.7
    max_agents: int = 15
    timeout_seconds: float = 30.0
    use_calibration: bool = True
    auto_research: bool = False  # v7: auto-execute research requests after decision


class DimensionScores(BaseModel):
    technical: float = 0.0
    user_impact: float = 0.0
    dev_speed: float = 0.0
    flexibility: float = 0.0
    risk: float = 0.0  # 0 = catastrophic failure likely, 10 = very safe

    def total(self) -> float:
        return (
            self.technical
            + self.user_impact
            + self.dev_speed
            + self.flexibility
            + self.risk
        )


class ResearchRequest(BaseModel):
    """An agent's request for external research to improve future decisions.

    Agents propose a specific topic they want investigated via web search.
    PM collects, deduplicates by topic similarity, sorts by votes.
    Team lead (or Gemini Pro researcher) executes the top request.
    Findings are injected into StructuredMemory World Network.
    """
    topic: str                      # specific research question (not vague)
    rationale: str = ""             # why this fills a gap in current knowledge
    proposed_by: str = ""           # agent_id that requested it
    domain: str = "general"         # domain this research belongs to
    priority: str = "medium"        # "high" | "medium" | "low"
    votes: int = 1                  # how many agents requested similar topic


class PathProposal(BaseModel):
    """A new path suggested by an agent that was not in the original config.

    Agents propose these when they see an important alternative the question didn't list.
    PM deduplicates and scores top proposals alongside original paths.
    """
    path_id: str = ""           # generated by PM: "prop_0", "prop_1", …
    name: str
    description: str
    rationale: str = ""         # why this path was overlooked
    proposed_by: str = ""       # agent_id that suggested it
    confidence: float = 0.0
    votes: int = 1              # how many agents independently suggested this


class AgentResult(BaseModel):
    agent_id: str              # e.g. "gemini-0", "groq-1"
    provider: str              # e.g. "gemini", "groq"
    model: str                 # e.g. "gemini-2.5-flash", "llama-3.3-70b"
    perspective: str = ""      # e.g. "pragmatist", "security"
    scores: dict[str, DimensionScores] = {}
    concerns: dict[str, str] = {}
    winner: str = ""
    reason: str = ""
    confidence: float = 0.0
    latency_ms: int = 0
    cost_estimate: float = 0.0
    json_valid: bool = False
    error: str | None = None
    raw_response: str = ""
    proposed_path: PathProposal | None = None      # optional path proposal (v5)
    held_firm: bool = False                         # v6: agent held vote after seeing graph
    research_request: ResearchRequest | None = None # v7: agent requests external research
    innovation: str = ""                            # v8: creative idea (was in prompt since v2, never stored)
    skill_used: str | None = None                   # v8: which skill was injected
    skill_helpful: bool | None = None               # v8: was the skill useful
    skill_gap: str | None = None                    # v8: what was missing from the skill
    self_note: str = ""                             # v8: agent's self-reflection


class DivergenceReport(BaseModel):
    winner_votes: dict[str, int] = {}
    top_winner: str = ""
    consensus_strength: float = 0.0  # 0.0-1.0
    is_genuine_consensus: bool = False
    high_divergence: bool = False     # > 0.6 threshold
    split_paths: list[str] = []


class ScalingEvent(BaseModel):
    round: int
    reason: str           # e.g. "divergence 0.65 > 0.6"
    agents_added: int
    provider_used: str


class SwarmReport(BaseModel):
    decision_id: str = ""
    config: SwarmConfig
    agents_used: int = 0
    agents_succeeded: int = 0
    agent_results: list[AgentResult] = []
    weighted_scores: dict[str, float] = {}  # path_id -> 0-50
    divergence: DivergenceReport = Field(default_factory=DivergenceReport)
    winner: str = ""
    winner_score: float = 0.0
    passed_confidence_gate: bool = False    # score >= 35
    scaling_events: list[ScalingEvent] = []
    synthesis: dict[str, Any] | None = None     # LLM synthesis result (MoA-style)
    provider_latencies: dict[str, float] = {}  # provider -> avg ms
    total_cost_estimate: float = 0.0
    total_latency_ms: int = 0
    accepted_proposals: list[PathProposal] = []    # agent-proposed paths that were scored (v5)
    research_requests: list[ResearchRequest] = []  # v7: research topics agents want investigated
    research_conducted: list[dict] = []            # v7: actual findings from web research
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ModelProfile(BaseModel):
    model_name: str
    provider: str
    base_weight: float = 1.0
    domain_weights: dict[str, float] = {}  # DomainTag.value -> weight
    total_evaluations: int = 0
    correct_predictions: int = 0
    accuracy: float = 0.5
    avg_latency_ms: float = 0.0
    avg_json_compliance: float = 1.0
    last_updated: str = ""

    # v6: sliding window calibration (replaces multiplicative death spiral)
    # Each entry: {"domain": "...", "correct": true/false, "decision_id": "..."}
    recent_outcomes: list[dict] = []  # last CALIBRATION_WINDOW outcomes
    CALIBRATION_WINDOW: int = 50  # only consider last 50 outcomes

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def get_weight(self, domain: DomainTag) -> float:
        """Get effective weight for a domain using sliding-window accuracy.

        v6 fix: instead of multiplicative w*=0.95 that death-spirals to floor,
        weight = 0.5 + recent_accuracy_in_domain. So:
          - 0% accuracy  → 0.5x (floor, still participates)
          - 50% accuracy → 1.0x (neutral)
          - 80% accuracy → 1.3x (strong)
          - 100% accuracy → 1.5x (cap)

        Minimum 5 outcomes in domain before diverging from 1.0 (base).
        """
        domain_outcomes = [
            o for o in self.recent_outcomes
            if o.get("domain") == domain.value
        ]
        if len(domain_outcomes) < 5:
            return self.base_weight

        correct = sum(1 for o in domain_outcomes if o.get("correct"))
        acc = correct / len(domain_outcomes)
        return round(0.5 + acc, 2)  # range: 0.5 to 1.5

    def record_outcome(self, domain: str, correct: bool, decision_id: str) -> None:
        """Record a calibration outcome in sliding window."""
        self.recent_outcomes.append({
            "domain": domain,
            "correct": correct,
            "decision_id": decision_id,
        })
        # Trim to window
        if len(self.recent_outcomes) > self.CALIBRATION_WINDOW:
            self.recent_outcomes = self.recent_outcomes[-self.CALIBRATION_WINDOW:]
        # Update accuracy
        correct_total = sum(1 for o in self.recent_outcomes if o.get("correct"))
        self.accuracy = correct_total / len(self.recent_outcomes)


class CalibrationEntry(BaseModel):
    decision_id: str
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    domain: DomainTag = DomainTag.GENERAL
    predicted_winner: str = ""
    predicted_score: float = 0.0
    actual_outcome: str = ""  # "better" | "worse" | "as_expected"
    models_correct: list[str] = []
    models_wrong: list[str] = []


class ProviderInfo(BaseModel):
    """Metadata about a provider's capabilities and limits."""
    name: str
    model: str
    cost_per_mtok_input: float = 0.0
    cost_per_mtok_output: float = 0.0
    rate_limit_rpm: int = 15
    is_free: bool = True
    supports_json_mode: bool = True
    priority: int = 0  # lower = preferred (free first)
