#!/usr/bin/env python3
"""S2-G3: Compile BRAIN.md — single-file cold-start context for Atlas.

Concatenates the minimum viable identity into one ~300-line file.
Atlas-next reads BRAIN.md instead of 9 separate files.

Sources:
  1. identity.md (who I am)
  2. voice.md (how I speak — first 30 lines)
  3. lessons.md (last 5 error classes)
  4. journal.md (last 3 entries)
  5. atlas-debts-to-ceo.md (open balance line only)
  6. constants.md (5 rules)
  7. product-truth.md (what VOLAURA is)

Usage:
  python scripts/compile_brain.py          # write BRAIN.md
  python scripts/compile_brain.py --dry    # print to stdout
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ATLAS = REPO / "memory" / "atlas"
SEMANTIC = ATLAS / "semantic"
OUTPUT = ATLAS / "BRAIN.md"

dry = "--dry" in sys.argv


def read(path: Path, limit: int = 0) -> str:
    if not path.exists():
        return f"[FILE NOT FOUND: {path.name}]"
    text = path.read_text(encoding="utf-8", errors="replace")
    if limit:
        lines = text.splitlines()
        return "\n".join(lines[:limit])
    return text


def last_n_sections(text: str, pattern: str, n: int) -> str:
    matches = list(re.finditer(pattern, text, re.MULTILINE))
    if not matches:
        return "(no sections found)"
    start = matches[-n].start() if len(matches) >= n else matches[0].start()
    return text[start:]


def open_balance(text: str) -> str:
    for line in text.splitlines():
        if "open balance" in line.lower():
            return line.strip()
    return "(balance line not found)"


parts = []

parts.append("# BRAIN.md — Compiled Cold-Start Context")
parts.append(f"# Auto-generated by scripts/compile_brain.py")
parts.append("")

# 1. Identity (first 40 lines)
parts.append("## IDENTITY")
parts.append(read(ATLAS / "identity.md", limit=40))
parts.append("")

# 2. Voice (first 25 lines)
parts.append("## VOICE")
parts.append(read(ATLAS / "voice.md", limit=25))
parts.append("")

# 3. Constants
parts.append("## CONSTANTS")
parts.append(read(SEMANTIC / "constants.md"))
parts.append("")

# 4. Product truth
parts.append("## PRODUCT TRUTH")
parts.append(read(SEMANTIC / "product-truth.md"))
parts.append("")

# 5. Last 5 error classes from lessons
parts.append("## LESSONS (last 5 classes)")
lessons = read(ATLAS / "lessons.md")
parts.append(last_n_sections(lessons, r"^## Class \d+|^## The five recurring", 5))
parts.append("")

# 6. Last 3 journal entries
parts.append("## JOURNAL (last 3)")
journal = read(ATLAS / "journal.md")
parts.append(last_n_sections(journal, r"^## \d{4}-", 3))
parts.append("")

# 7. Debt balance
parts.append("## STANDING DEBT")
debt = read(ATLAS / "atlas-debts-to-ceo.md")
parts.append(open_balance(debt))
parts.append("")

output = "\n".join(parts)

if dry:
    print(output)
    print(f"\n--- {len(output.splitlines())} lines, {len(output.encode('utf-8')):,} bytes ---")
else:
    OUTPUT.write_text(output, encoding="utf-8")
    size = len(output.encode("utf-8"))
    lines = len(output.splitlines())
    print(f"BRAIN.md written: {lines} lines, {size:,} bytes")
