"""One-time migration: retranslate all AZ content using Google Translation LLM.

Research finding (2026-03-31): All existing AZ translations were generated by raw Claude
which produces grammatically incorrect Azerbaijani (wrong case suffixes, unnatural word order
for agglutinative structure). This script replaces them with Google Translation LLM output.

Usage:
    # Dry run (shows what would change, doesn't write)
    python scripts/fix_az_translations.py --dry-run

    # Fix questions table (scenario_az, feedback_az, development_tip_az, options text_az)
    python scripts/fix_az_translations.py --table questions

    # Fix i18n JSON files
    python scripts/fix_az_translations.py --table i18n

    # Fix everything
    python scripts/fix_az_translations.py --all

Prerequisites:
    1. Set SUPABASE_URL + SUPABASE_SERVICE_KEY in apps/api/.env
    2. Set GEMINI_API_KEY (fallback path — works today with no extra setup)
    3. Optional: Set GCP_PROJECT_ID + GOOGLE_APPLICATION_CREDENTIALS for best quality
"""

import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Optional

# Add API app to path
sys.path.insert(0, str(Path(__file__).parent.parent / "apps" / "api"))

from loguru import logger

# Configure logging
logger.remove()
logger.add(sys.stdout, format="{time:HH:mm:ss} | {level} | {message}", level="INFO")

# Fields in questions table that contain AZ text
QUESTION_AZ_FIELDS = [
    "scenario_az",
    "feedback_az",
    "development_tip_az",
]

# i18n files to process
I18N_AZ_FILE = Path(__file__).parent.parent / "apps" / "web" / "src" / "locales" / "az" / "common.json"
I18N_EN_FILE = Path(__file__).parent.parent / "apps" / "web" / "src" / "locales" / "en" / "common.json"


async def fix_questions_table(dry_run: bool = True, limit: Optional[int] = None) -> dict:
    """Retranslate AZ fields in the questions table."""
    from app.config import settings
    from app.services.az_translation import translate_en_to_az
    from supabase._async.client import AsyncClient
    from supabase import acreate_client

    client: AsyncClient = await acreate_client(settings.supabase_url, settings.supabase_service_key)

    # Fetch questions
    query = client.table("questions").select(
        "id, scenario_en, scenario_az, feedback_en, feedback_az, "
        "development_tip_en, development_tip_az, options"
    )
    if limit:
        query = query.limit(limit)

    result = await query.execute()
    questions = result.data or []
    logger.info(f"Found {len(questions)} questions to process")

    stats = {"total": len(questions), "updated": 0, "skipped": 0, "errors": 0}

    for i, q in enumerate(questions):
        qid = q["id"]
        updates = {}

        # Translate main text fields
        field_pairs = [
            ("scenario_en", "scenario_az"),
            ("feedback_en", "feedback_az"),
            ("development_tip_en", "development_tip_az"),
        ]
        for en_field, az_field in field_pairs:
            en_text = q.get(en_field, "")
            if not en_text:
                continue
            try:
                new_az = await translate_en_to_az(
                    en_text,
                    context="professional competency assessment question for Volaura platform",
                )
                if new_az and new_az != en_text:  # en_text fallback means translation failed
                    updates[az_field] = new_az
            except Exception as e:
                logger.error(f"  Error translating {az_field} for {qid}: {e}")
                stats["errors"] += 1

        # Translate options (JSON array with text_en/text_az per option)
        options_raw = q.get("options")
        if options_raw:
            try:
                options = json.loads(options_raw) if isinstance(options_raw, str) else options_raw
                updated_options = []
                for opt in options:
                    new_opt = dict(opt)
                    if opt.get("text_en"):
                        new_az = await translate_en_to_az(
                            opt["text_en"],
                            context="answer option for professional assessment question",
                        )
                        if new_az and new_az != opt["text_en"]:
                            new_opt["text_az"] = new_az
                    updated_options.append(new_opt)
                updates["options"] = json.dumps(updated_options, ensure_ascii=False)
            except Exception as e:
                logger.error(f"  Error translating options for {qid}: {e}")
                stats["errors"] += 1

        if updates:
            if not dry_run:
                await client.table("questions").update(updates).eq("id", qid).execute()
                stats["updated"] += 1
            else:
                stats["updated"] += 1
                # Show first example
                if i == 0:
                    for k, v in updates.items():
                        if k != "options":
                            logger.info(f"  [DRY RUN] {k}: {str(v)[:100]}...")
        else:
            stats["skipped"] += 1

        if (i + 1) % 10 == 0:
            logger.info(f"  Progress: {i + 1}/{len(questions)} ({stats['updated']} updated, {stats['errors']} errors)")

    logger.info(f"Questions done: {stats}")
    return stats


async def fix_i18n_file(dry_run: bool = True) -> dict:
    """Retranslate az/common.json using en/common.json as source."""
    from app.services.az_translation import batch_translate_en_to_az

    if not I18N_EN_FILE.exists():
        logger.error(f"EN i18n file not found: {I18N_EN_FILE}")
        return {"error": "EN file not found"}
    if not I18N_AZ_FILE.exists():
        logger.error(f"AZ i18n file not found: {I18N_AZ_FILE}")
        return {"error": "AZ file not found"}

    with open(I18N_EN_FILE, encoding="utf-8") as f:
        en_data = json.load(f)
    with open(I18N_AZ_FILE, encoding="utf-8") as f:
        az_data = json.load(f)

    def _flatten(d: dict, prefix: str = "") -> dict[str, str]:
        """Flatten nested dict to dot-notation keys."""
        result = {}
        for k, v in d.items():
            key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                result.update(_flatten(v, key))
            elif isinstance(v, str):
                result[key] = v
        return result

    def _unflatten(flat: dict[str, str]) -> dict:
        """Unflatten dot-notation keys back to nested dict."""
        result: dict = {}
        for key, value in flat.items():
            parts = key.split(".")
            d = result
            for part in parts[:-1]:
                d = d.setdefault(part, {})
            d[parts[-1]] = value
        return result

    en_flat = _flatten(en_data)
    az_flat = _flatten(az_data)

    # Find keys that need translation (all EN strings)
    keys_to_translate = list(en_flat.keys())
    en_texts = [en_flat[k] for k in keys_to_translate]

    logger.info(f"Translating {len(keys_to_translate)} i18n strings...")

    if not dry_run:
        az_texts = await batch_translate_en_to_az(
            en_texts,
            context="UI text for professional talent assessment platform, formal register",
            concurrency=3,
        )
        new_az_flat = dict(zip(keys_to_translate, az_texts))
        new_az_data = _unflatten(new_az_flat)

        with open(I18N_AZ_FILE, "w", encoding="utf-8") as f:
            json.dump(new_az_data, f, ensure_ascii=False, indent=2)
        logger.info(f"Written {len(new_az_flat)} translations to {I18N_AZ_FILE}")
    else:
        # Show 3 examples
        for k in keys_to_translate[:3]:
            logger.info(f"  [DRY RUN] {k}: {en_flat[k][:60]} → (would translate)")

    return {"total": len(keys_to_translate), "updated": len(keys_to_translate) if not dry_run else 0}


async def main():
    import argparse

    parser = argparse.ArgumentParser(description="Fix AZ translations in Volaura")
    parser.add_argument("--dry-run", action="store_true", default=True, help="Show changes without writing")
    parser.add_argument("--execute", action="store_true", help="Actually write changes (overrides --dry-run)")
    parser.add_argument("--table", choices=["questions", "i18n"], help="Which data to fix")
    parser.add_argument("--all", action="store_true", help="Fix everything")
    parser.add_argument("--limit", type=int, help="Limit questions processed (for testing)")
    args = parser.parse_args()

    dry_run = not args.execute
    if dry_run:
        logger.info("=== DRY RUN MODE — no changes will be written. Use --execute to apply. ===")

    if args.all or args.table == "questions":
        logger.info("--- Fixing questions table ---")
        await fix_questions_table(dry_run=dry_run, limit=args.limit)

    if args.all or args.table == "i18n":
        logger.info("--- Fixing i18n AZ file ---")
        await fix_i18n_file(dry_run=dry_run)

    if not args.all and not args.table:
        logger.info("No target specified. Use --table questions, --table i18n, or --all")
        logger.info("Add --execute to actually write changes (default is dry-run)")


if __name__ == "__main__":
    asyncio.run(main())
