-- Lifesim events table + seed — Life Feed inside VOLAURA (M1 step 2)
-- Source: docs/life-simulator/events/godot-export-2026-04-15.json (53 events)
-- Per docs/LIFE-SIMULATOR-REIMAGINE-2026-04-15.md Path C

CREATE TABLE IF NOT EXISTS public.lifesim_events (
    id              TEXT PRIMARY KEY,
    category        TEXT NOT NULL,
    title_ru        TEXT NOT NULL,
    description_ru  TEXT NOT NULL,
    min_age         INT,
    max_age         INT,
    required_stats  JSONB NOT NULL DEFAULT '{}'::jsonb,
    choices         JSONB NOT NULL DEFAULT '[]'::jsonb,
    extra           JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lifesim_events_category ON public.lifesim_events(category) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_lifesim_events_age ON public.lifesim_events(min_age, max_age) WHERE is_active = TRUE;

ALTER TABLE public.lifesim_events ENABLE ROW LEVEL SECURITY;

-- Event pool is public to all authenticated users (read-only).
-- Only service_role writes via /lifesim admin endpoints (future).
DROP POLICY IF EXISTS "lifesim_events_read_all" ON public.lifesim_events;
CREATE POLICY "lifesim_events_read_all" ON public.lifesim_events
    FOR SELECT
    USING (auth.role() IS NOT NULL);

COMMENT ON TABLE public.lifesim_events IS 'Life Simulator event pool — 53 events extracted from Godot project 2026-04-15. Served to Life Feed surface in VOLAURA web. Read-only to users, writes via service_role only.';

-- Seed 53 events from canonical JSON
-- INSERT ... ON CONFLICT DO NOTHING so re-runs are idempotent
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_school_001', 'education', 'Экзамен в школе', 'Завтра важный экзамен. От результатов зависит твоё дальнейшее образование.', 6, 17, '{}'::jsonb, '[{"text_ru": "Усердно готовиться всю ночь", "consequences": {"intelligence": 10, "energy": -30, "health": -10, "happiness": -5}}, {"text_ru": "Готовиться умеренно, высыпаться", "consequences": {"intelligence": 5, "energy": -10, "health": 5, "happiness": 10}}, {"text_ru": "Попросить помощи у умных друзей", "consequences": {"intelligence": 3, "energy": -15, "social": 20, "happiness": 5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 7, "tags": ["school", "exam", "education"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_university_001', 'education', 'Поступление в университет', 'Пришло время выбирать университет. Твои оценки и результаты тестов определят доступные специальности.', 17, 25, '{"intelligence": 60}'::jsonb, '[{"text_ru": "Поступить в престижный университет", "consequences": {"money": -25000, "intelligence": 20, "work_experience": 10, "social": 15, "happiness": 30}}, {"text_ru": "Выбрать бюджетный вариант", "consequences": {"money": -8000, "intelligence": 15, "work_experience": 5, "social": 10, "happiness": 20}}, {"text_ru": "Отложить поступление на год", "consequences": {"money": 5000, "energy": 20, "social": 5, "happiness": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["university", "education", "milestone"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_graduation_001', 'education', 'Выпускной экзамен', 'Последний экзамен в университете. Диплом зависит от результатов этого теста.', 21, 30, '{}'::jsonb, '[{"text_ru": "Готовиться на отлично", "consequences": {"intelligence": 15, "energy": -40, "health": -15, "money": -5000, "happiness": 20}}, {"text_ru": "Сфокусироваться на проходной балл", "consequences": {"intelligence": 8, "energy": -25, "health": -5, "money": -2000, "happiness": 15}}, {"text_ru": "Попросить помощи у одногруппников", "consequences": {"intelligence": 5, "energy": -15, "social": 25, "money": -1000, "happiness": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["graduation", "exam", "milestone"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_master_degree_001', 'education', 'Магистратура', 'Тебе предлагают продолжить обучение в магистратуре. Это откроет новые карьерные возможности.', 23, 35, '{"intelligence": 75, "work_experience": 20}'::jsonb, '[{"text_ru": "Поступить в магистратуру", "consequences": {"money": -30000, "intelligence": 25, "work_experience": 15, "energy": -30, "happiness": 25}}, {"text_ru": "Выбрать онлайн-формат", "consequences": {"money": -15000, "intelligence": 20, "work_experience": 10, "energy": -20, "happiness": 20}}, {"text_ru": "Отказаться и сосредоточиться на карьере", "consequences": {"money": 10000, "work_experience": 20, "energy": 20, "social": 5, "happiness": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["master", "education", "career"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_skills_course_001', 'education', 'Курсы повышения квалификации', 'Возможность пройти курсы для получения новых навыков и сертификата.', 25, 55, '{}'::jsonb, '[{"text_ru": "Пройти интенсивные курсы", "consequences": {"money": -12000, "intelligence": 12, "work_experience": 15, "energy": -20, "happiness": 15}}, {"text_ru": "Выбрать вечерние курсы", "consequences": {"money": -8000, "intelligence": 8, "work_experience": 10, "energy": -15, "happiness": 10}}, {"text_ru": "Изучать самостоятельно", "consequences": {"money": -3000, "intelligence": 5, "work_experience": 5, "energy": -10, "happiness": 5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 14, "tags": ["courses", "skills", "self_improvement"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_language_001', 'education', 'Изучение иностранного языка', 'Изучение нового языка откроет возможности для работы и путешествий.', 18, 50, '{}'::jsonb, '[{"text_ru": "Записаться на интенсивные курсы", "consequences": {"money": -20000, "intelligence": 15, "social": 10, "energy": -25, "happiness": 20}}, {"text_ru": "Выбрать онлайн-обучение", "consequences": {"money": -10000, "intelligence": 10, "social": 5, "energy": -15, "happiness": 15}}, {"text_ru": "Практиковаться с носителями", "consequences": {"money": -5000, "intelligence": 8, "social": 20, "energy": -10, "happiness": 10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["language", "education", "skills"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('edu_phd_001', 'education', 'Аспирантура', 'Преподаватель предлагает тебе поступить в аспирантуру. Путь к научной степени.', 28, 40, '{"intelligence": 85, "work_experience": 30}'::jsonb, '[{"text_ru": "Поступить в аспирантуру", "consequences": {"money": -40000, "intelligence": 30, "work_experience": 20, "energy": -35, "happiness": 30}}, {"text_ru": "Выбрать заочную форму", "consequences": {"money": -25000, "intelligence": 25, "work_experience": 15, "energy": -25, "happiness": 20}}, {"text_ru": "Отказаться ради карьеры", "consequences": {"money": 15000, "work_experience": 25, "energy": 20, "social": 5, "happiness": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["phd", "research", "academic"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('health_cold_001', 'health', 'Простуда', 'Ты простудился. Горло болит, температура повышена, и нет сил даже вставать с кровати.', 0, 100, '{}'::jsonb, '[{"text_ru": "Лечиться дома", "consequences": {"health": 25, "energy": -15, "money": -20, "happiness": -5}}, {"text_ru": "Вызвать врача", "consequences": {"health": 45, "energy": -10, "money": -150, "happiness": 5}}, {"text_ru": "Игнорировать", "consequences": {"health": -30, "energy": -20, "happiness": -15, "work_experience": -5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 7, "tags": ["illness", "recovery"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('health_injury_001', 'health', 'Спортивная травма', 'Во время пробежки ты подвернул ногу. Боль острая, движение ограничено.', 15, 60, '{}'::jsonb, '[{"text_ru": "Обратиться в травмпункт", "consequences": {"health": 60, "energy": -25, "money": -100, "work_experience": 5}}, {"text_ru": "Лечиться дома", "consequences": {"health": 30, "energy": -15, "money": -50, "work_experience": -3}}, {"text_ru": "Продолжать тренировки", "consequences": {"health": -40, "energy": -30, "work_experience": 10, "social": -5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 14, "tags": ["injury", "sports"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('health_stress_001', 'health', 'Выгорание на работе', 'Постоянные дедлайны и давление привели к эмоциональному выгоранию. Ты чувствуешь себя опустошенным.', 25, 65, '{"work_experience": 50}'::jsonb, '[{"text_ru": "Взять отпуск", "consequences": {"health": 20, "energy": 30, "happiness": 25, "money": -500, "work_experience": -10}}, {"text_ru": "Сменить работу", "consequences": {"health": 15, "energy": 20, "happiness": 20, "money": -200, "work_experience": -20}}, {"text_ru": "Продолжать в том же духе", "consequences": {"health": -25, "energy": -35, "happiness": -30, "work_experience": 15, "social": -10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["stress", "work"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('health_chronic_001', 'health', 'Хроническое заболевание', 'У тебя обнаружили хроническое заболевание, требующее постоянного лечения.', 40, 100, '{}'::jsonb, '[{"text_ru": "Начать дорогое лечение", "consequences": {"health": 70, "energy": -20, "money": -1000, "happiness": -10}}, {"text_ru": "Использовать народные средства", "consequences": {"health": 30, "energy": -10, "money": -100, "happiness": 5}}, {"text_ru": "Игнорировать проблему", "consequences": {"health": -50, "energy": -15, "happiness": -20, "intelligence": -5}}]'::jsonb, '{"is_repeatable": false, "tags": ["chronic", "serious"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('health_addiction_001', 'health', 'Зависимость от соцсетей', 'Ты проводишь слишком много времени в соцсетях, это начинает влиять на твою жизнь.', 16, 35, '{}'::jsonb, '[{"text_ru": "Установить лимит времени", "consequences": {"health": 10, "energy": 15, "happiness": 20, "intelligence": 5, "social": -10}}, {"text_ru": "Полностью отказаться от соцсетей", "consequences": {"health": 25, "energy": 30, "happiness": -15, "social": -30, "intelligence": 10}}, {"text_ru": "Продолжить как раньше", "consequences": {"health": -20, "energy": -25, "happiness": -10, "social": 5, "intelligence": -10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 10, "tags": ["addiction", "social_media"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('health_aging_001', 'health', 'Возрастные изменения', 'С возрастом твоё тело меняется. Появляются новые болячки и ограничения.', 50, 100, '{}'::jsonb, '[{"text_ru": "Начать здоровый образ жизни", "consequences": {"health": 30, "energy": 20, "happiness": 15, "money": -300}}, {"text_ru": "Принять изменения", "consequences": {"health": 10, "energy": -10, "happiness": -5}}, {"text_ru": "Обратиться к врачам", "consequences": {"health": 40, "energy": -15, "money": -500, "happiness": 10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 30, "tags": ["aging", "natural"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_birth_001', 'milestone', 'Рождение', 'Ты только что родился! Мир огромен и полон возможностей.', 0, 0, '{}'::jsonb, '[{"text_ru": "Громко плакать (здоровый ребёнок)", "consequences": {"health": 10, "energy": 10, "happiness": 10}}, {"text_ru": "Спать спокойно (спокойный ребёнок)", "consequences": {"health": 5, "energy": 15, "happiness": 5}}]'::jsonb, '{"is_repeatable": false, "tags": ["birth", "milestone", "beginning"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_first_steps_001', 'milestone', 'Первые шаги', 'Ты делаешь первые неуверенные шаги. Родители в восторге от твоих достижений.', 1, 2, '{}'::jsonb, '[{"text_ru": "Сделать шаг к маме", "consequences": {"health": 5, "energy": 5, "happiness": 15, "social": 10}}, {"text_ru": "Сделать шаг к папе", "consequences": {"health": 5, "energy": 5, "happiness": 15, "social": 10}}, {"text_ru": "Упасть и сесть", "consequences": {"health": 3, "energy": 8, "happiness": 5}}]'::jsonb, '{"is_repeatable": false, "tags": ["first_steps", "milestone", "development"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_first_school_001', 'milestone', 'Первый день в школе', 'Ты впервые идёшь в школу. Новые друзья, знания и переживания ждут тебя.', 6, 8, '{}'::jsonb, '[{"text_ru": "С энтузиазмом пойти в класс", "consequences": {"intelligence": 10, "social": 20, "happiness": 20, "energy": -10}}, {"text_ru": "Осторожно осмотреться", "consequences": {"intelligence": 5, "social": 10, "happiness": 10, "energy": -5}}, {"text_ru": "Попросить маму остаться", "consequences": {"intelligence": 2, "social": 5, "happiness": 5, "energy": 5}}]'::jsonb, '{"is_repeatable": false, "tags": ["school", "milestone", "education"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_teenager_001', 'milestone', 'Подростковый возраст', 'Ты вступаешь в сложный подростковый период. Гормональные изменения и поиск себя.', 13, 17, '{}'::jsonb, '[{"text_ru": "Найти своё хобби", "consequences": {"intelligence": 8, "social": 15, "happiness": 25, "energy": -10}}, {"text_ru": "Проводить время с друзьями", "consequences": {"intelligence": 3, "social": 30, "happiness": 20, "energy": -15}}, {"text_ru": "Уделить время учёбе", "consequences": {"intelligence": 15, "social": 5, "happiness": 10, "energy": -5}}]'::jsonb, '{"is_repeatable": false, "tags": ["teenager", "milestone", "development"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_adulthood_001', 'milestone', 'Совершеннолетие', 'Тебе исполнилось 18 лет! Перед тобой открыт мир взрослых возможностей и ответственности.', 18, 18, '{}'::jsonb, '[{"text_ru": "Отметить с друзьями", "consequences": {"money": -5000, "happiness": 40, "social": 35, "energy": -20}}, {"text_ru": "Начать планировать будущее", "consequences": {"intelligence": 20, "happiness": 25, "energy": -10, "work_experience": 10}}, {"text_ru": "Поговорить с родителями о жизни", "consequences": {"social": 25, "happiness": 20, "energy": 5}}]'::jsonb, '{"is_repeatable": false, "tags": ["adulthood", "milestone", "freedom"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_first_love_001', 'milestone', 'Первая любовь', 'Ты впервые испытываешь чувства любви. Это красиво, страшно и волнующе одновременно.', 16, 25, '{}'::jsonb, '[{"text_ru": "Признаться в чувствах", "consequences": {"happiness": 50, "social": 25, "energy": -15, "intelligence": 5}}, {"text_ru": "Скрыть свои чувства", "consequences": {"happiness": 20, "social": 10, "energy": -5, "intelligence": 10}}, {"text_ru": "Посоветоваться с друзьями", "consequences": {"happiness": 30, "social": 35, "energy": -10, "intelligence": 8}}]'::jsonb, '{"is_repeatable": false, "tags": ["first_love", "milestone", "romance"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_first_job_001', 'milestone', 'Первая работа', 'Ты получил(а) первую работу. Старт карьеры и финансовой независимости.', 16, 22, '{}'::jsonb, '[{"text_ru": "Работать усердно", "consequences": {"money": 8000, "work_experience": 25, "energy": -30, "happiness": 20, "social": -10}}, {"text_ru": "Найти баланс работой и личной жизнью", "consequences": {"money": 5000, "work_experience": 15, "energy": -15, "happiness": 25, "social": 10}}, {"text_ru": "Учиться у коллег", "consequences": {"money": 6000, "work_experience": 20, "intelligence": 15, "energy": -20, "happiness": 15}}]'::jsonb, '{"is_repeatable": false, "tags": ["first_job", "milestone", "career"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_midlife_001', 'milestone', 'Кризис среднего возраста', 'Ты задаёшься вопросами о смысле жизни и своих достижениях. Кризис среднего возраста.', 40, 55, '{}'::jsonb, '[{"text_ru": "Найти новые цели в жизни", "consequences": {"happiness": 35, "intelligence": 20, "energy": 15, "social": 15}}, {"text_ru": "Сменить окружение", "consequences": {"money": -10000, "happiness": 25, "social": 30, "energy": 10}}, {"text_ru": "Принять текущую жизнь", "consequences": {"happiness": 20, "energy": 20, "social": 10, "intelligence": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["midlife_crisis", "milestone", "philosophy"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_retirement_001', 'milestone', 'Выход на пенсию', 'Ты уходишь на пенсию. Новая глава жизни после долгой карьеры.', 60, 70, '{}'::jsonb, '[{"text_ru": "Путешествовать по миру", "consequences": {"money": -30000, "happiness": 50, "social": 20, "energy": 20, "health": 10}}, {"text_ru": "Заняться хобби", "consequences": {"money": -10000, "happiness": 40, "energy": 15, "social": 25, "intelligence": 15}}, {"text_ru": "Работать консультантом", "consequences": {"money": 15000, "work_experience": 20, "happiness": 30, "energy": 10, "social": 20}}]'::jsonb, '{"is_repeatable": false, "tags": ["retirement", "milestone", "new_beginning"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('milestone_death_001', 'milestone', 'Конец жизни', 'Ты подходишь к концу своего жизненного пути. Время подводить итоги.', 70, 100, '{}'::jsonb, '[{"text_ru": "Принять судьбу с достоинством", "consequences": {"happiness": 50, "social": 30, "peace": 100}}, {"text_ru": "Бороться до последнего", "consequences": {"health": 20, "happiness": 20, "energy": 20, "peace": 50}}, {"text_ru": "Просить прощения у близких", "consequences": {"happiness": 35, "social": 50, "peace": 80}}]'::jsonb, '{"is_repeatable": false, "tags": ["death", "milestone", "ending"], "category_code": 8}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_lottery_001', 'random', 'Выигрыш в лотерею', 'Ты случайно проверил старый лотерейный билет и обнаружил, что ты выиграл крупную сумму!', 18, 100, '{}'::jsonb, '[{"text_ru": "Получить выигрыш немедленно", "consequences": {"money": 100000, "happiness": 50, "social": 20, "energy": 10}}, {"text_ru": "Потратить всё на развлечения", "consequences": {"money": -80000, "happiness": 80, "social": 40, "energy": -20, "health": -10}}, {"text_ru": "Инвестировать в бизнес", "consequences": {"money": -50000, "work_experience": 30, "intelligence": 15, "energy": -15, "happiness": 20}}]'::jsonb, '{"is_repeatable": false, "tags": ["lottery", "money", "luck"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_inheritance_001', 'random', 'Наследство', 'Дальний родственник оставил тебе наследство. Это неожиданный, но приятный сюрприз.', 25, 80, '{}'::jsonb, '[{"text_ru": "Принять наследство и жить достойно", "consequences": {"money": 200000, "happiness": 30, "social": 15, "energy": 10}}, {"text_ru": "Пожертвовать часть на благотворительность", "consequences": {"money": 150000, "happiness": 50, "social": 25, "intelligence": 10, "energy": 5}}, {"text_ru": "Инвестировать в образование", "consequences": {"money": 180000, "intelligence": 25, "work_experience": 15, "energy": -10, "happiness": 20}}]'::jsonb, '{"is_repeatable": false, "tags": ["inheritance", "money", "family"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_found_pet_001', 'random', 'Находка - домашний питомец', 'Ты нашёл бездомное животное, которое нуждается в заботе и любви.', 10, 70, '{}'::jsonb, '[{"text_ru": "Забрать животное домой", "consequences": {"money": -5000, "happiness": 40, "social": 15, "energy": -15, "health": 10}}, {"text_ru": "Отнести в приют", "consequences": {"money": -1000, "happiness": 20, "social": 10, "energy": -5, "intelligence": 5}}, {"text_ru": "Найти хозяина", "consequences": {"money": 2000, "happiness": 15, "social": 5, "energy": -5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 30, "tags": ["pet", "animal", "compassion"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_travel_001', 'random', 'Случайное путешествие', 'Представилась неожиданная возможность отправиться в путешествие со скидкой 80%.', 20, 65, '{"money": 10000}'::jsonb, '[{"text_ru": "Отправиться в путешествие", "consequences": {"money": -8000, "happiness": 60, "social": 20, "energy": -20, "intelligence": 10}}, {"text_ru": "Взять с собой друга", "consequences": {"money": -12000, "happiness": 50, "social": 35, "energy": -25, "health": 5}}, {"text_ru": "Отказаться ради работы", "consequences": {"money": 2000, "work_experience": 10, "energy": 10, "happiness": -10, "social": -5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["travel", "opportunity", "experience"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_hobby_001', 'random', 'Новое хобби', 'Ты открыл для себя новое увлечение, которое приносит радость и развивает навыки.', 15, 80, '{}'::jsonb, '[{"text_ru": "Посвятить всё свободное время хобби", "consequences": {"money": -3000, "happiness": 35, "intelligence": 15, "energy": -20, "social": -10}}, {"text_ru": "Найти баланс с работой", "consequences": {"money": -1500, "happiness": 20, "intelligence": 8, "energy": -10, "social": 5}}, {"text_ru": "Превратить хобби в источник дохода", "consequences": {"money": 5000, "work_experience": 20, "intelligence": 10, "energy": -15, "happiness": 25}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 14, "tags": ["hobby", "skills", "self_development"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_neighbor_001', 'random', 'Соседские отношения', 'Твои соседи организуют вечеринку и приглашают тебя присоединиться.', 18, 100, '{}'::jsonb, '[{"text_ru": "Пойти на вечеринку", "consequences": {"money": -2000, "happiness": 30, "social": 35, "energy": -25, "health": -5}}, {"text_ru": "Познакомиться с соседями", "consequences": {"money": -500, "happiness": 15, "social": 25, "energy": -10, "health": 5}}, {"text_ru": "Вежливо отказаться", "consequences": {"money": 0, "happiness": -5, "social": -10, "energy": 10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 7, "tags": ["neighbors", "social", "community"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_famous_001', 'random', 'Встреча со знаменитостью', 'Ты случайно встретил известного человека, который может повлиять на твою жизнь.', 20, 80, '{}'::jsonb, '[{"text_ru": "Попросить автограф и селфи", "consequences": {"happiness": 40, "social": 30, "energy": -10, "intelligence": 5}}, {"text_ru": "Предложить сотрудничество", "consequences": {"money": 10000, "work_experience": 25, "social": 40, "energy": -20, "happiness": 50}}, {"text_ru": "Просто пожелать удачи", "consequences": {"happiness": 15, "social": 15, "energy": 5}}]'::jsonb, '{"is_repeatable": false, "tags": ["famous", "opportunity", "luck"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('random_investment_001', 'random', 'Инвестиционная возможность', 'Тебе представили уникальную возможность инвестировать в перспективный стартап.', 25, 70, '{"money": 50000, "intelligence": 70}'::jsonb, '[{"text_ru": "Вложить все сбережения", "consequences": {"money": -45000, "work_experience": 20, "intelligence": 10, "energy": -15, "happiness": 20}}, {"text_ru": "Вложить половину сбережений", "consequences": {"money": -25000, "work_experience": 15, "intelligence": 8, "energy": -10, "happiness": 15}}, {"text_ru": "Отказаться от риска", "consequences": {"money": 2000, "happiness": 5, "energy": 10, "social": 5}}]'::jsonb, '{"is_repeatable": false, "tags": ["investment", "business", "risk"], "category_code": 1}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_parent_crisis_001', 'relationship', 'Проблемы с родителями', 'Твои родители переживают трудный период и просят твоей помощи и поддержки.', 16, 40, '{}'::jsonb, '[{"text_ru": "Помочь финансово", "consequences": {"money": -10000, "social": 25, "happiness": 15, "energy": -20}}, {"text_ru": "Провести больше времени с ними", "consequences": {"money": -3000, "social": 30, "happiness": 20, "energy": -15}}, {"text_ru": "Посоветовать обратиться к специалистам", "consequences": {"money": -1000, "social": 15, "happiness": 10, "energy": -5}}]'::jsonb, '{"modifies_relationships": ["parent"], "is_repeatable": true, "cooldown_days": 14, "tags": ["family", "parents", "support"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_friend_help_001', 'relationship', 'Друг просит о помощи', 'Твой лучший друг оказался в сложной ситуации и отчаянно просит твоей помощи.', 18, 100, '{}'::jsonb, '[{"text_ru": "Оказать полную поддержку", "consequences": {"money": -15000, "social": 35, "happiness": 25, "energy": -25}}, {"text_ru": "Помочь финансово, но не лично", "consequences": {"money": -8000, "social": 20, "happiness": 15, "energy": -10}}, {"text_ru": "Посоветовать обратиться к профессионалам", "consequences": {"money": -500, "social": 10, "happiness": 5, "energy": -5}}]'::jsonb, '{"modifies_relationships": ["best_friend"], "is_repeatable": true, "cooldown_days": 10, "tags": ["friendship", "help", "crisis"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_romance_001', 'relationship', 'Новое знакомство', 'Ты познакомился с интересным человеком. Возникает симпатия и желание продолжить общение.', 16, 50, '{"social": 40}'::jsonb, '[{"text_ru": "Пригласить на свидание", "consequences": {"money": -3000, "social": 25, "happiness": 30, "energy": -15}}, {"text_ru": "Предложить дружбу", "consequences": {"money": -1000, "social": 20, "happiness": 15, "energy": -10}}, {"text_ru": "Оставить просто знакомым", "consequences": {"money": 0, "social": 5, "happiness": 5, "energy": -5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 7, "tags": ["romance", "dating", "opportunity"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_conflict_001', 'relationship', 'Конфликт с другом', 'Из-за недопонимания возник конфликт с близким другом. Отношения под угрозой.', 18, 100, '{}'::jsonb, '[{"text_ru": "Попытаться примириться", "consequences": {"money": -1000, "social": 20, "happiness": 15, "energy": -10}}, {"text_ru": "Дать время остыть", "consequences": {"money": 0, "social": -10, "happiness": -10, "energy": 10}}, {"text_ru": "Обратиться к общим друзьям", "consequences": {"money": -500, "social": 15, "happiness": 10, "energy": -5}}]'::jsonb, '{"modifies_relationships": ["friend"], "is_repeatable": true, "cooldown_days": 14, "tags": ["conflict", "friendship", "crisis"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_marriage_001', 'relationship', 'Предложение о браке', 'Твой партнер делает тебе предложение о браке. Это важное решение, которое изменит твою жизнь.', 22, 45, '{}'::jsonb, '[{"text_ru": "Согласиться на брак", "consequences": {"money": -20000, "social": 40, "happiness": 50, "energy": -20}}, {"text_ru": "Предложить пожить вместе сначала", "consequences": {"money": -5000, "social": 30, "happiness": 35, "energy": -15}}, {"text_ru": "Вежливо отказаться", "consequences": {"money": 2000, "social": -30, "happiness": -25, "energy": 10}}]'::jsonb, '{"required_relationships": {"partner": 80}, "is_repeatable": false, "tags": ["marriage", "commitment", "milestone"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_betrayal_001', 'relationship', 'Предательство', 'Человек, которому ты доверял, предал тебя. Это болезненный удар по твоим убеждениям.', 20, 100, '{}'::jsonb, '[{"text_ru": "Простить и попытаться сохранить отношения", "consequences": {"money": -2000, "social": 15, "happiness": -10, "energy": -10}}, {"text_ru": "Разорвать все отношения", "consequences": {"money": 0, "social": -40, "happiness": -30, "energy": 5}}, {"text_ru": "Потребовать объяснений", "consequences": {"money": -1000, "social": 5, "happiness": -5, "energy": -5}}]'::jsonb, '{"is_repeatable": false, "tags": ["betrayal", "trust", "crisis"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_family_event_001', 'relationship', 'Семейное торжество', 'В твоей семье намечается важное событие - юбилей, свадьба или рождение ребёнка.', 18, 100, '{}'::jsonb, '[{"text_ru": "Активно участвовать в организации", "consequences": {"money": -5000, "social": 30, "happiness": 25, "energy": -25}}, {"text_ru": "Помочь финансово", "consequences": {"money": -10000, "social": 20, "happiness": 15, "energy": -15}}, {"text_ru": "Просто присутствовать", "consequences": {"money": -2000, "social": 15, "happiness": 10, "energy": -10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["family", "celebration", "positive"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('rel_childbirth_001', 'relationship', 'Рождение ребёнка', 'У тебя родился ребёнок! Это радость, но и огромная ответственность.', 25, 45, '{}'::jsonb, '[{"text_ru": "Взять отпуск по уходу за ребёнком", "consequences": {"money": -15000, "social": 20, "happiness": 40, "energy": -30}}, {"text_ru": "Нанять няню", "consequences": {"money": -8000, "social": 10, "happiness": 30, "energy": -20}}, {"text_ru": "Просить помощи у родственников", "consequences": {"money": -5000, "social": 25, "happiness": 25, "energy": -25}}]'::jsonb, '{"required_relationships": {"partner": 90}, "is_repeatable": false, "tags": ["childbirth", "family", "milestone"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('volaura_gold_recruit_001', 'volaura', 'Приглашение от организации', 'Международная организация нашла твой профиль на VOLAURA и видит, что у тебя Gold-уровень. Предлагают позицию с отличными условиями.', 20, 55, '{"intelligence": 60, "social": 40}'::jsonb, '[{"text_ru": "Принять предложение", "consequences": {"money": 40000, "work_experience": 35, "happiness": 40, "social": 20, "energy": -20}}, {"text_ru": "Обсудить условия", "consequences": {"money": 55000, "work_experience": 25, "happiness": 30, "social": 15, "energy": -10}}, {"text_ru": "Вежливо отказать — не моё направление", "consequences": {"happiness": 10, "social": 5, "energy": 10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 30, "tags": ["volaura", "recruitment", "career"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('volaura_assessment_unlock_001', 'volaura', 'Новый уровень AURA', 'Твои результаты на VOLAURA улучшились! Ты разблокировал доступ к продвинутым курсам и менторским программам.', 18, 80, '{"intelligence": 40}'::jsonb, '[{"text_ru": "Пройти продвинутый курс", "consequences": {"money": -5000, "intelligence": 25, "work_experience": 15, "energy": -25, "happiness": 20}}, {"text_ru": "Найти ментора", "consequences": {"money": -3000, "intelligence": 15, "social": 20, "work_experience": 10, "energy": -15}}, {"text_ru": "Поделиться успехом в социальных сетях", "consequences": {"social": 30, "happiness": 15, "energy": -5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["volaura", "assessment", "growth"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('volaura_crystal_course_001', 'volaura', 'Кристаллы — премиум обучение', 'У тебя накопилось достаточно кристаллов VOLAURA, чтобы разблокировать премиум-курс по лидерству.', 18, 60, '{"money": 5000}'::jsonb, '[{"text_ru": "Потратить кристаллы на курс", "consequences": {"money": -2000, "intelligence": 20, "social": 15, "work_experience": 20, "energy": -20, "happiness": 15}}, {"text_ru": "Копить кристаллы на что-то большее", "consequences": {"money": 1000, "happiness": 5, "energy": 5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 14, "tags": ["volaura", "crystals", "education"], "category_code": 4}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('volaura_platinum_event_001', 'volaura', 'Platinum — элитный нетворкинг', 'Как обладатель Platinum-бейджа VOLAURA, ты приглашён на закрытое мероприятие для топ-специалистов. Здесь собираются CEO, инвесторы и лидеры индустрии.', 25, 65, '{"intelligence": 80, "social": 60}'::jsonb, '[{"text_ru": "Пойти и завести связи", "consequences": {"money": -5000, "social": 45, "work_experience": 20, "happiness": 35, "energy": -30}}, {"text_ru": "Предложить свой стартап инвесторам", "consequences": {"money": 50000, "work_experience": 30, "social": 25, "happiness": 50, "energy": -40}}, {"text_ru": "Пропустить — слишком формально для меня", "consequences": {"energy": 15, "happiness": -5, "social": -10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 30, "tags": ["volaura", "platinum", "networking", "elite"], "category_code": 5}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('volaura_mindshift_streak_001', 'volaura', 'MindShift — серия фокус-сессий', 'Ты прошёл 7-дневную серию фокус-сессий в MindShift. Твоя концентрация и энергия заметно улучшились.', 16, 80, '{}'::jsonb, '[{"text_ru": "Продолжить серию — цель 30 дней", "consequences": {"health": 20, "energy": 25, "intelligence": 10, "happiness": 20, "money": -1000}}, {"text_ru": "Применить навыки на работе", "consequences": {"work_experience": 20, "energy": 15, "intelligence": 5, "money": 5000}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 7, "tags": ["mindshift", "focus", "health", "ecosystem"], "category_code": 10}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('volaura_career_coach_001', 'volaura', 'Карьерный коуч VOLAURA', 'VOLAURA предлагает услуги AI-карьерного коуча на основе твоего AURA-профиля. Гарантия следующего повышения.', 22, 50, '{"money": 7500}'::jsonb, '[{"text_ru": "Нанять коуча (75 кристаллов)", "consequences": {"money": -7500, "work_experience": 30, "intelligence": 10, "happiness": 20, "social": 10}}, {"text_ru": "Попробовать бесплатную консультацию", "consequences": {"work_experience": 10, "intelligence": 5, "happiness": 10, "energy": -5}}, {"text_ru": "Разобраться самому", "consequences": {"intelligence": 15, "energy": -15, "happiness": 5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["volaura", "career", "coaching", "crystals"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_promotion_001', 'work', 'Повышение на работе', 'Твой начальник заметил твою хорошую работу и предлагает повышение с увеличением зарплаты.', 22, 65, '{"work_experience": 30}'::jsonb, '[{"text_ru": "Согласиться на повышение", "consequences": {"money": 15000, "work_experience": 20, "energy": -20, "social": -5, "happiness": 25}}, {"text_ru": "Попросить о большей зарплате", "consequences": {"money": 20000, "work_experience": 15, "energy": -15, "social": -10, "happiness": 20}}, {"text_ru": "Вежливо отказаться", "consequences": {"money": 5000, "work_experience": 5, "energy": 10, "social": 15, "happiness": 10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 14, "tags": ["promotion", "career"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_new_job_001', 'work', 'Предложение о новой работе', 'Тебе предложили работу в конкурирующей компании с лучшими условиями.', 20, 55, '{}'::jsonb, '[{"text_ru": "Перейти в новую компанию", "consequences": {"money": 25000, "work_experience": 25, "energy": -25, "social": -15, "happiness": 30}}, {"text_ru": "Попросить текущего работодателя о повышении", "consequences": {"money": 10000, "work_experience": 10, "energy": -10, "social": 5, "happiness": 15}}, {"text_ru": "Остаться на текущей работе", "consequences": {"money": 5000, "work_experience": 5, "energy": 5, "social": 10, "happiness": 5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["job_change", "opportunity"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_layoff_001', 'work', 'Увольнение', 'Компания сокращает штат, и твоя должность попала под сокращение.', 25, 65, '{}'::jsonb, '[{"text_ru": "Получить пособие по безработице", "consequences": {"money": 15000, "energy": 20, "happiness": -20, "work_experience": -10}}, {"text_ru": "Искать новую работу немедленно", "consequences": {"money": 8000, "energy": -30, "happiness": -10, "work_experience": 5}}, {"text_ru": "Открыть свой бизнес", "consequences": {"money": -20000, "energy": -40, "happiness": 10, "work_experience": 30, "intelligence": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["layoff", "crisis"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_overtime_001', 'work', 'Сверхурочная работа', 'Начальник просит остаться после работы для срочного проекта. Дополнительная оплата гарантирована.', 22, 60, '{"energy": 50}'::jsonb, '[{"text_ru": "Согласиться на сверхурочные", "consequences": {"money": 5000, "work_experience": 10, "energy": -40, "happiness": -15, "health": -10}}, {"text_ru": "Вежливо отказаться", "consequences": {"money": 1000, "energy": 10, "happiness": 5, "social": 5}}, {"text_ru": "Попросить о двойной оплате", "consequences": {"money": 8000, "work_experience": 8, "energy": -35, "happiness": -5, "health": -15}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 7, "tags": ["overtime", "money"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_project_001', 'work', 'Важный проект', 'Тебе поручили ответственный проект, который определит твою карьеру в компании.', 25, 65, '{"work_experience": 40}'::jsonb, '[{"text_ru": "Взяться за проект с энтузиазмом", "consequences": {"money": 10000, "work_experience": 30, "energy": -50, "happiness": -20, "health": -20, "intelligence": 5}}, {"text_ru": "Работать стабильно, без лишнего стресса", "consequences": {"money": 7000, "work_experience": 15, "energy": -25, "happiness": 5, "health": 5}}, {"text_ru": "Делегировать часть работы", "consequences": {"money": 5000, "work_experience": 10, "energy": -15, "happiness": 10, "social": 10}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 14, "tags": ["project", "career"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_training_001', 'work', 'Корпоративное обучение', 'Компания предлагает пройти обучение для повышения квалификации. От тебя потребуется полное погружение.', 20, 55, '{}'::jsonb, '[{"text_ru": "Согласиться на обучение", "consequences": {"money": -2000, "work_experience": 25, "energy": -30, "intelligence": 15, "happiness": 10}}, {"text_ru": "Попросить о онлайн-формате", "consequences": {"money": -1000, "work_experience": 15, "energy": -15, "intelligence": 8, "happiness": 15}}, {"text_ru": "Отказаться от обучения", "consequences": {"money": 2000, "work_experience": -5, "energy": 10, "happiness": -5, "social": 5}}]'::jsonb, '{"is_repeatable": true, "cooldown_days": 21, "tags": ["training", "education"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_burnout_001', 'work', 'Профессиональное выгорание', 'Многолетняя работа в одной сфере привела к потере интереса и мотивации.', 30, 60, '{"work_experience": 60}'::jsonb, '[{"text_ru": "Взять длительный отпуск", "consequences": {"money": -8000, "work_experience": -15, "energy": 40, "happiness": 30, "health": 20}}, {"text_ru": "Сменить профессию", "consequences": {"money": -15000, "work_experience": -30, "energy": 20, "happiness": 25, "intelligence": 10}}, {"text_ru": "Найти хобби для разнообразия", "consequences": {"money": -2000, "work_experience": -5, "energy": 15, "happiness": 20, "social": 10}}]'::jsonb, '{"is_repeatable": false, "tags": ["burnout", "crisis"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.lifesim_events (id, category, title_ru, description_ru, min_age, max_age, required_stats, choices, extra)
VALUES ('work_startup_001', 'work', 'Стартап', 'Тебе пришла идея для собственного бизнеса. Риски высоки, но потенциальная награда огромна.', 25, 45, '{"intelligence": 70, "work_experience": 50}'::jsonb, '[{"text_ru": "Основать стартап", "consequences": {"money": -50000, "work_experience": 50, "energy": -60, "happiness": 40, "intelligence": 20, "social": -20}}, {"text_ru": "Сначала накопить капитал", "consequences": {"money": -10000, "work_experience": 10, "energy": -10, "happiness": 10, "social": 5}}, {"text_ru": "Найти партнёров", "consequences": {"money": -20000, "work_experience": 25, "energy": -30, "happiness": 25, "social": 15}}]'::jsonb, '{"is_repeatable": false, "tags": ["startup", "entrepreneurship"], "category_code": 3}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Total seeded: 53 events
